channels:
- conda-forge
dependencies:
- python=3.12.4
- pip<=24.0
- pip:
  - mlflow==3.1.1
  - cffi==1.17.1
  - cloudpickle==3.1.1
  - lightgbm==4.6.0
  - matplotlib==3.10.3
  - numpy==2.2.6
  - pandas==2.3.1
  - psutil==7.0.0
  - pyarrow==20.0.0
  - scikit-learn==1.6.1
  - scipy==1.16.0
name: mlflow-env
